modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/Fellteros/mossify/issues"
license = "CC BY-SA 4.0"

[[mods]]
modId = "mossify"
version = "${version}"
displayName = "Mossify"
authors = "Fellter"
description = '''
'Mossify' blocks with moss blocks and scrape it with an axe
'''
logoFile = "assets/mossify/icon.png"

[[dependencies.mossify]]
modId = "neoforge"
mandatory = true
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mossify]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.8,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "mossify.mixins.json"
